### ISSUE TITLE
Wrong icon used in home screen

### ISSUE THREAD

**Issue by tripu** [guibbs/w3c-tpac2016#16]
When I add the app to the home screen (Nexus 5, CyanogenMod 13, Android 6.0.1, Firefox Beta), the icon that gets added is _not_ [`assets/img/app-icon.png`](https://github.com/w3c/tpac2016/blob/gh-pages/manifest.json#L6), but the _favicon_. (It is uglier and doesn't scale well.)

**Comment by gbaudusseau** [comment]
hmm I have no clue about this...

**Comment by tripu** [comment]
More details (HW and OS same as above):
- **Firefox Beta**: wrong icon (favicon is used).
- **Chrome Dev**: right icon, but _only when adding from the &ldquo;home&rdquo; screen_. If I &ldquo;add to home screen&rdquo; from eg the schedule page, the icon that gets added is a generic white-uppercase-G-letter-on-plain-orange-background icon.

**Comment by gbaudusseau** [comment]
ok it came from an error on the schedule page. @tripu can you check again and let me know if it works now? thanks man! (feel free to close the issue if it works)

**Comment by tripu** [comment]
Fixed for me in Chrome in all cases, but still failing in Firefox.

I reloaded the page. Can anyone else test with FF?

@marcoscaceres, anything obvious we're missing here&hellip;?

**Comment by marcoscaceres** [comment]
Will try to have a look tomorrow. Travelling ATM

**Comment by marcoscaceres** [comment]
Sorry for the delay. Firefox doesn't use the manifest yet, unfortunately... you will just get the favicon. Maybe by TPAC it will be supported. Just focus on the Chrome and iOS support for now.

**Comment by tripu** [comment]
Thanks, @marcoscaceres!
