### ISSUE TITLE
Wrong start page when added to home screen?

### ISSUE THREAD

**Issue by tripu** [guibbs/w3c-tpac2016#17]
When I add the app to the home screen (Nexus 5, CyanogenMod 13, Android 6.0.1, Firefox Beta), the initial page seems to depend on the page I'm visiting _in that moment_. ie, I now have two &ldquo;shortcuts&rdquo; on my home screen with identical (wrong, cf #16) icon: one for the home page, and another one for the schedule (the two pages I visited when I tried that feature).

**Comment by gbaudusseau** [comment]
I think I made a mistake within the `manifest.json` file. let me check.

**Comment by tripu** [comment]
It happens too with Chrome Dev (same HW and OS as above).

**Comment by gbaudusseau** [comment]
@tripu feel free to reopen the issue if it still doesn't work properly for you.

**Comment by tripu** [comment]
:+1:
