### ISSUE TITLE
Use of rows in schedule isn't intuitive

### ISSUE THREAD

**Issue by tripu** [guibbs/w3c-tpac2016#18]
- If rows are _clickable_ to reveal more information, make it more apparent? (not sure how; in desktop a `cursor: pointer` would help).
- The meaning of the greyed-out times underneath the main ones isn't entirely clear (to me).

**Comment by gbaudusseau** [comment]
So, only the arrow on the right of each row is clickable, not the entire row. The greyed area will contain details about the specific schedule. for example, if it's a group meeting schedule it will display the rooms, attendees etc...

Does that make sense?

**Comment by gbaudusseau** [comment]
but you're right for the `cursor:pointer` I forgot to use that property :)

**Comment by tripu** [comment]
> So, only the arrow on the right of each row is clickable, not the entire row.

Oh. Is it an arrow?? I thought it was a clock, and was wondering why the hands dropped when you expanded the row!? :sweat_smile:

OK, so if it's an arrow (and other people _see_ that), I guess it's a bit more clear than it's clickable.

**Comment by gbaudusseau** [comment]
added `cursor:pointer` on it :)

Yeah man you're the first one to think it was a clock haha.
